From bugzilla-daemon at main.slony.info  Mon May  2 00:39:34 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Mon,  2 May 2011 00:39:34 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 202] remote_worker error creating log cursor
In-Reply-To: <bug-202-4@http.www.slony.info/bugzilla/>
References: <bug-202-4@http.www.slony.info/bugzilla/>
Message-ID: <20110502073934.D215F290D92@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=202

--- Comment #6 from Jason Tevnan <jason.tevnan at apex-gaming.com> 2011-05-02 00:39:34 PDT ---
(In reply to comment #5)
> As far as I can tell, this is erroneous data produces by Postgres itself. Slony
> uses txid_current_snapshot() to get that snapshot datum, which now apparently
> cannot pass through a data type output+input cycle.
> 
> I'm going to run a few tests this afternoon and contact the PG hackers list
> after that.

Did your tests offer any explanations for this behavior?

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed May  4 08:47:13 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed,  4 May 2011 08:47:13 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 90] Error while running "make" for Slony 2.0 on
	Solaris 2.11
In-Reply-To: <bug-90-4@http.www.slony.info/bugzilla/>
References: <bug-90-4@http.www.slony.info/bugzilla/>
Message-ID: <20110504154713.262E3290CDA@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=90

Steve Singer <ssinger at ca.afilias.info> changed:

           What    |Removed                     |Added
----------------------------------------------------------------------------
         Resolution|                            |FIXED
             Status|REOPENED                    |RESOLVED

--- Comment #8 from Steve Singer <ssinger at ca.afilias.info> 2011-05-04 08:47:12 PDT ---
In 2.1 I feel this commit includes fixes to address SUN C Studio builds on
Solaris

http://git.postgresql.org/gitweb?p=slony1-engine.git;a=commitdiff;h=275a2eaddf995e3376b8fb42dad5c199a6a98bfc

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed May  4 08:48:53 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed,  4 May 2011 08:48:53 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 179] Implicit WAIT FOR EVENT
In-Reply-To: <bug-179-4@http.www.slony.info/bugzilla/>
References: <bug-179-4@http.www.slony.info/bugzilla/>
Message-ID: <20110504154853.7BF5E290D75@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=179

Steve Singer <ssinger at ca.afilias.info> changed:

           What    |Removed                     |Added
----------------------------------------------------------------------------
         Resolution|                            |FIXED
             Status|ASSIGNED                    |RESOLVED

--- Comment #8 from Steve Singer <ssinger at ca.afilias.info> 2011-05-04 08:48:53 PDT ---
Committed to master for 2.1 at 

http://git.postgresql.org/gitweb?p=slony1-engine.git;a=commitdiff;h=29a509489ed665d18ad66c441a6aea4378507e65

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.

From bugzilla-daemon at main.slony.info  Wed May  4 08:48:53 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed,  4 May 2011 08:48:53 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 171] Health Check: Verify node's parentage
In-Reply-To: <bug-171-4@http.www.slony.info/bugzilla/>
References: <bug-171-4@http.www.slony.info/bugzilla/>
Message-ID: <20110504154853.EE97C290D98@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=171

Bug 171 depends on bug 179, which changed state.

Bug 179 Summary: Implicit WAIT FOR EVENT
http://www.slony.info/bugzilla/show_bug.cgi?id=179

           What    |Old Value                   |New Value
----------------------------------------------------------------------------
             Status|NEW                         |ASSIGNED
         Resolution|                            |FIXED
             Status|ASSIGNED                    |RESOLVED

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed May  4 08:48:54 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed,  4 May 2011 08:48:54 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 178] More sophisticated FAILOVER
In-Reply-To: <bug-178-4@http.www.slony.info/bugzilla/>
References: <bug-178-4@http.www.slony.info/bugzilla/>
Message-ID: <20110504154854.68FA5290DAA@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=178

Bug 178 depends on bug 179, which changed state.

Bug 179 Summary: Implicit WAIT FOR EVENT
http://www.slony.info/bugzilla/show_bug.cgi?id=179

           What    |Old Value                   |New Value
----------------------------------------------------------------------------
             Status|NEW                         |ASSIGNED
         Resolution|                            |FIXED
             Status|ASSIGNED                    |RESOLVED

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.

From bugzilla-daemon at main.slony.info  Wed May  4 12:27:56 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed,  4 May 2011 12:27:56 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 203] New: Use of "name" type conflicts with
	pg_upgrade
Message-ID: <bug-203-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=203

           Summary: Use of "name" type conflicts with pg_upgrade
           Product: Slony-I
           Version: devel
          Platform: All
        OS/Version: All
            Status: NEW
          Severity: enhancement
          Priority: low
         Component: core scripts
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: cbbrowne at ca.afilias.info
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


Various columns in the Slony schema that store relation names use the "name"
type.

According to PostgreSQL docs:

http://www.postgresql.org/docs/9.0/static/datatype-character.html

"The name type exists only for the storage of identifiers in the internal
system catalogs and is not intended for use by the general user. Its length is
currently defined as 64 bytes (63 usable characters plus terminator) but should
be referenced using the constant NAMEDATALEN in C source code."

There is some room to quibble over whether Slony is an "internal system" thing
or a "general user," but it has been observed that the use of the name type
adversely affects attempts to run pg_upgrade against Slony nodes.

http://lists.slony.info/pipermail/slony1-general/2011-April/011620.html

It seems as though we should switch from "name" to "text".

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Thu May  5 13:13:12 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Thu,  5 May 2011 13:13:12 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 137] execute script does not get applied in the
	correct order
In-Reply-To: <bug-137-4@http.www.slony.info/bugzilla/>
References: <bug-137-4@http.www.slony.info/bugzilla/>
Message-ID: <20110505201312.14278290310@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=137

Christopher Browne <cbbrowne at ca.afilias.info> changed:

           What    |Removed                     |Added
----------------------------------------------------------------------------
         AssignedTo|slony1-bugs at lists.slony.inf |cbbrowne at ca.afilias.info
                   |o                           |
             Status|NEW                         |ASSIGNED

--- Comment #6 from Christopher Browne <cbbrowne at ca.afilias.info> 2011-05-05 13:13:11 PDT ---
I am "poking away" at this; see branch at GitHub:

https://github.com/cbbrowne/slony1-engine/tree/bug137

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Fri May  6 09:05:54 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Fri,  6 May 2011 09:05:54 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 204] New: Failover to a non-direct subscriber
	fails
Message-ID: <bug-204-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=204

           Summary: Failover to a non-direct subscriber fails
           Product: Slony-I
           Version: 2.0
          Platform: PC
        OS/Version: Linux
            Status: NEW
          Severity: enhancement
          Priority: low
         Component: stored procedures
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: ssinger at ca.afilias.info
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


In 2.0.5, 2.0.6 failover to a non direct subscriber fails. It leaves nodes with
sl_subscribe entries to the backup_node as both a provider and a receiver.

Commit 7970189ec93faf3ee71cf49e97529980bbd219aa says that it removed a repeated
UPDATE statement.  The update statement removed was actually slightly different
than the one above it.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Fri May  6 09:10:19 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Fri,  6 May 2011 09:10:19 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 204] Failover to a non-direct subscriber fails
In-Reply-To: <bug-204-4@http.www.slony.info/bugzilla/>
References: <bug-204-4@http.www.slony.info/bugzilla/>
Message-ID: <20110506161019.D4EA6290D85@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=204

--- Comment #1 from Steve Singer <ssinger at ca.afilias.info> 2011-05-06 09:10:19 PDT ---
Created an attachment (id=94)
 --> (http://www.slony.info/bugzilla/attachment.cgi?id=94)
patch for bug 204

Patch for bug 204.
I propose this for both master and REL_2_0_STABLE

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Mon May  9 13:09:49 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Mon,  9 May 2011 13:09:49 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 205] New: Upgrade to 2.1.0b1 fails
Message-ID: <bug-205-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=205

           Summary: Upgrade to 2.1.0b1 fails
           Product: Slony-I
           Version: devel
          Platform: PC
        OS/Version: Linux
            Status: NEW
          Severity: enhancement
          Priority: low
         Component: stored procedures
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: ssinger at ca.afilias.info
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


I tried upgrading my slony 2.0.6 cluster to 2.1 and it failed with

---------------------------

All of Slony-I is successfully installed
ssinger at ssinger-laptop:~/src/slony1-engine/slony1-engine$ slonik
include<test.preamble>
upgrade functions(id=1);
<stdin>:2: ERROR: syntax error at or near upgrade
ssinger at ssinger-laptop:~/src/slony1-engine/slony1-engine$ slonik
include<test.preamble>
update functions(id=1);
<stdin>:2: WARNING:  This node is running PostgreSQL 8.3 - cannot apply
TRUNCATE triggers
CONTEXT:  SQL statement "SELECT  "_test".add_truncate_triggers()"
PL/pgSQL function "upgradeschema" line 11 at PERFORM
<stdin>:2: NOTICE:  Changing Slony-I column [sl_event.ev_timestamp] to
timestamp WITH time zone
<stdin>:2: PGRES_FATAL_ERROR select "_test".upgradeSchema('2.0.6');  - ERROR: 
syntax error at or near "data"
LINE 1: ...le "_test".sl_event alter column ev_timestamp set data type ...
                                                             ^
QUERY:  alter table "_test".sl_event alter column ev_timestamp set data type
timestamp with time zone;
CONTEXT:  PL/pgSQL function "upgradeschema" line 33 at EXECUTE statement
ssinger at ssinger-laptop:~/src/slony1-engine/slony1-engine$

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Mon May  9 13:40:43 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Mon,  9 May 2011 13:40:43 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 206] New: Upgrade from 2.0.0 to 2.1.0b1 fails
Message-ID: <bug-206-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=206

           Summary: Upgrade from 2.0.0 to 2.1.0b1 fails
           Product: Slony-I
           Version: devel
          Platform: PC
        OS/Version: Linux
            Status: NEW
          Severity: enhancement
          Priority: low
         Component: stored procedures
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: ssinger at ca.afilias.info
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


ssinger at ssinger-laptop:~/src/slony1-engine/slony1-engine$ slonik
include<test.preamble>
update functions(id=1);
<stdin>:2: loading of file /usr/local/pgsql8.3/share//slony1_funcs.sql:
PGRES_FATAL_ERROR ERROR:  cannot change return type of existing function
HINT:  Use DROP FUNCTION first.
ERROR:  cannot change return type of existing function
HINT:  Use DROP FUNCTION first.
-------------------------------------


This happens even with a fix to bug 205 applied.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Tue May 10 08:42:58 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Tue, 10 May 2011 08:42:58 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 207] New: create set in a try block rollsback
Message-ID: <bug-207-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=207

           Summary: create set in a try block rollsback
           Product: Slony-I
           Version: devel
          Platform: PC
        OS/Version: Linux
            Status: NEW
          Severity: enhancement
          Priority: low
         Component: slonik
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: ssinger at ca.afilias.info
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


In 2.1.0.b1

include<test.preamble>
try {
create set(id=2, origin=2);
set add sequence(set id=2, sequences='public.a*');
subscribe set(id=2,provider=2,receiver=3);
subscribe set(id=2,provider=2,receiver=1);
merge set(id=1,add id=2,origin=2);
}
on error {
echo 'error';
}

goes to the on error block with

tmp/x:4: PGRES_FATAL_ERROR select "_test".setAddSequence(2, 1,
'public.a_a_seq', 'replicated sequence');  - ERROR:  Slony-I: setAddSequence():
set 2 not found
/tmp/x:2 Error: waiting operation not allowed inside of inside of a try
block/tmp/x:9: erorr


After the storeSet function is called but before the setAddSequence() function
is invoked the database transaction is rolledback (for some unknown reason)

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Tue May 10 10:10:41 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Tue, 10 May 2011 10:10:41 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 207] create set in a try block rollsback
In-Reply-To: <bug-207-4@http.www.slony.info/bugzilla/>
References: <bug-207-4@http.www.slony.info/bugzilla/>
Message-ID: <20110510171041.19128290D89@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=207

--- Comment #1 from Steve Singer <ssinger at ca.afilias.info> 2011-05-10 10:10:41 PDT ---
Created an attachment (id=95)
 --> (http://www.slony.info/bugzilla/attachment.cgi?id=95)
Fix for bug 207

Attach is a fix for 207.
Some please review

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Tue May 10 11:19:11 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Tue, 10 May 2011 11:19:11 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 207] create set in a try block rollsback
In-Reply-To: <bug-207-4@http.www.slony.info/bugzilla/>
References: <bug-207-4@http.www.slony.info/bugzilla/>
Message-ID: <20110510181911.A682C290D89@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=207

Christopher Browne <cbbrowne at ca.afilias.info> changed:

           What    |Removed                     |Added
----------------------------------------------------------------------------
         AssignedTo|slony1-bugs at lists.slony.inf |ssinger at ca.afilias.info
                   |o                           |
             Status|NEW                         |ASSIGNED

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Tue May 10 11:54:06 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Tue, 10 May 2011 11:54:06 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 207] create set in a try block rollsback
In-Reply-To: <bug-207-4@http.www.slony.info/bugzilla/>
References: <bug-207-4@http.www.slony.info/bugzilla/>
Message-ID: <20110510185406.2065F290D9C@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=207

--- Comment #2 from Christopher Browne <cbbrowne at ca.afilias.info> 2011-05-10 11:54:06 PDT ---
Some questions...

1.  Is there an existing test that moves from "broken" to "working" as a result
of this patch?

'Twould be really nice to have such.

2.  I'm not thrilled with the complications that this adds, particularly when
they're not named much.  Quite a bit of indirection involved.

I added comments to slonik_wait_config_caughtup() to indicate interpretation of
its return results, which better indicates why the change is needful.

3.  I noticed a number of references to [64] as the length of names.  This is
correct, but not descriptive.

Postgres has a #define for NAMEDATALEN to indicate this; I have adopted and
applied that.

It compiles, and looks reasonable, but I haven't tested it.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.

From bugzilla-daemon at main.slony.info  Tue May 10 11:55:22 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Tue, 10 May 2011 11:55:22 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 207] create set in a try block rollsback
In-Reply-To: <bug-207-4@http.www.slony.info/bugzilla/>
References: <bug-207-4@http.www.slony.info/bugzilla/>
Message-ID: <20110510185522.D87E3290D9A@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=207

--- Comment #3 from Christopher Browne <cbbrowne at ca.afilias.info> 2011-05-10 11:55:23 PDT ---
Here's a reference to my patch.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.

From bugzilla-daemon at main.slony.info  Tue May 10 14:21:01 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Tue, 10 May 2011 14:21:01 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 208] New: default table id doesn't work in
	2.1.0.b1
Message-ID: <bug-208-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=208

           Summary: default table id doesn't work in 2.1.0.b1
           Product: Slony-I
           Version: devel
          Platform: PC
        OS/Version: Linux
            Status: NEW
          Severity: enhancement
          Priority: low
         Component: slonik
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: ssinger at ca.afilias.info
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


The slonik command
--------------
set add table(set id=1, tables='public.x.*' , add sequences=true);

fails with

set add table(set id=1, tables='public.x.*' , add sequences=true);
<stdin>:2: PGRES_FATAL_ERROR select "_test".setAddTable(1, -1, '', 'x0_pkey',
'replicated table');  - ERROR:  Slony-I: setAddTable_int(): table  not found
CONTEXT:  SQL statement "SELECT  "_test".setAddTable_int( $1 ,  $2 ,  $3 ,  $4
,  $5 )"
PL/pgSQL function "setaddtable" line 32 at PERFORM

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed May 11 02:52:21 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed, 11 May 2011 02:52:21 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 209] New: PGRES_FATAL_ERROR ERROR when
 installing slony in postgresql 7.4.30 DB
Message-ID: <bug-209-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=209

           Summary: PGRES_FATAL_ERROR ERROR when installing slony in
                    postgresql 7.4.30 DB
           Product: Slony-I
           Version: 1.2
          Platform: All
        OS/Version: Linux
            Status: NEW
          Severity: major
          Priority: low
         Component: stored procedures
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: smorris328 at gmail.com
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


Created an attachment (id=96)
 --> (http://www.slony.info/bugzilla/attachment.cgi?id=96)
Script used to initialise slony

When installing slony into a postgresql 7.4.30 DB I got the following error:

<stdin>:21: loading of file
/home/smorris/postgresql/pgsql7430/bin//../share//slony1_funcs.v74.sql:
PGRES_FATAL_ERROR ERROR:  syntax error at or near "$" at character 4337
ERROR:  syntax error at or near "$" at character 4337

Having investigated this further it looks to me like the last function in the
/share//slony1_funcs.v74.sql file is not in the correct format for a 7.4.*
database.

I have altered it to:

create or replace function @NAMESPACE at .TruncateOnlyTable ( name) returns void
as
'
begin
    execute ''truncate ''|| @NAMESPACE at .slon_quote_input($1);
end;
'
LANGUAGE plpgsql;

and this seems to work.

I have attached my initialisation script.

Stuart

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed May 11 08:45:31 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed, 11 May 2011 08:45:31 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 207] create set in a try block rollsback
In-Reply-To: <bug-207-4@http.www.slony.info/bugzilla/>
References: <bug-207-4@http.www.slony.info/bugzilla/>
Message-ID: <20110511154531.5CBEB29017F@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=207

--- Comment #4 from Christopher Browne <cbbrowne at ca.afilias.info> 2011-05-11 08:45:30 PDT ---
Perhaps I need to actually link the branch/patch.

https://github.com/cbbrowne/slony1-engine/tree/bug207

https://github.com/cbbrowne/slony1-engine/commit/56fed94cd6d47bd8ead787408e4129664941cd78

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.

From bugzilla-daemon at main.slony.info  Wed May 11 12:01:11 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed, 11 May 2011 12:01:11 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 209] PGRES_FATAL_ERROR ERROR when installing
 slony in postgresql 7.4.30 DB
In-Reply-To: <bug-209-4@http.www.slony.info/bugzilla/>
References: <bug-209-4@http.www.slony.info/bugzilla/>
Message-ID: <20110511190111.8F612290335@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=209

Christopher Browne <cbbrowne at ca.afilias.info> changed:

           What    |Removed                     |Added
----------------------------------------------------------------------------
         Resolution|                            |FIXED
             Status|NEW                         |RESOLVED

--- Comment #1 from Christopher Browne <cbbrowne at ca.afilias.info> 2011-05-11 12:01:11 PDT ---
Fixed in 1.2 branch:

http://git.postgresql.org/gitweb?p=slony1-engine.git;a=commit;h=e4b4d5783c20e17bf688081d15dc4866a4a7d28e

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

